x-logging: &logging
  logging:
    options:
      max-size: 10m
      max-file: "10"

services:
  moonchain_client_prover:
    image: us-docker.pkg.dev/mxczkevm/images/moonchain-client:moonchain-geneva
    restart: always
    networks:
     - mxc_node_net
    env_file:
      - .env
    volumes:
      - ./script:/script
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-prover-relayer.sh"
    depends_on:
      - moonchain_prover_manager
    <<: *logging

  moonchain_prover_manager:
    image: us-docker.pkg.dev/mxczkevm/images/prover-manager:latest
#    image: moonchain/prover-manager:local
    restart: always
    env_file:
      - .env
    ports:
      - 8181:8181
    networks:
     - mxc_node_net
    <<: *logging

  mysql:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./mysql/data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
     - mxc_node_net
    <<: *logging

  influxdb:
    image: influxdb:2.7
    env_file:
      - .env
    volumes:
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
      # Data mounting
      - ./influxdb/data:/var/lib/influxdb2 
    networks:
     - mxc_node_net
    <<: *logging

networks:
 mxc_node_net:
   driver: bridge
   ipam:
     config:
       - subnet: 172.21.0.0/16
